#!/usr/bin/env bash

# Remove a python venv environment
function rmvenv() {
    echo "$1"
    # Usage
    if [ ! -n "$1" ]; then
        echo "Usage: rmvenv <venv_name>"
        return 1
    fi

    # Test if in correct directory (i.e deleting the correct venv) 
    local activate="$1/bin/activate"
    if [ ! -f "$activate" ]; then
        echo "Error: $activate does not exist, make sure you are in the right directory!"
        return 2
    fi

    # `deactivate` should only exist if you've already activated the environment, so test if it exists, then deactivate
    declare -f -F deactivate > /dev/null && (deactivate; echo "Deactivated $1 environment")

    # Remove environment directory
    rm -r "./$1"
    echo "Removed $1 environment"
}
