#!/usr/bin/env bash

# Create and activate a python venv environment 
function venv() {
    # Usage
    if [ ! -n "$1" ]; then
        echo "Usage: venv <venv_name>"
        return 1
    fi

    # If the venv doesn't exist yet, create it
    local activate="$1/bin/activate"
    if [ ! -f "$activate" ]; then
        python -m venv "$1"
        echo "Created $1 environment"
    fi

    # Activate the venv 
    source $1/bin/activate
    echo "Activated $1 environment"
}
